version: '3.8'

services:
  portfolio:
    image: nginx:stable
    container_name: portfolio-site
    volumes:
      - ./front-end/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl:ro
    ports:
      - "443:443"
    restart: always
